Update Allwmake

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -1,39 +1,151 @@
 #!/bin/sh
 
-cd QGD; wmake libso; cd ../
+cd QGD; wmake libso
+rc=$?
+if [ "$rc" = '0' ]; then
+    echo "QGD compiled"
+else
+    echo "QGD compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd TwoPhaseQGD; wmake libso; cd ../
+cd TwoPhaseQGD; wmake libso
+if [ "$rc" = '0' ]; then
+    echo "twoPhaseQGD compiled"
+else
+    echo "twoPhaseQGD compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd CombustionQGD; wmake libso; cd ../
+cd CombustionQGD; wmake libso
+if [ "$rc" = '0' ]; then
+    echo "CombustionQGD compiled"
+else
+    echo "CombustionQGD compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd ChemistryQGD; wmake libso; cd ../
+cd ChemistryQGD; wmake libso
+if [ "$rc" = '0' ]; then
+    echo "ChemistryQGD compiled"
+else
+    echo "ChemistryQGD compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd QGDFoam; ./Allwmake; cd ../
+cd QGDFoam; ./Allwmake
+if [ "$rc" = '0' ]; then
+    echo "QGDFoam compiled"
+else
+    echo "QGDFoam compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd QHDFoam; ./Allwmake; cd ../
+cd QHDFoam; ./Allwmake
+if [ "$rc" = '0' ]; then
+    echo "QHDFoam compiled"
+else
+    echo "QHDFoam compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd mulesQHDFoam; ./Allwmake; cd ../
+cd mulesQHDFoam; ./Allwmake
+if [ "$rc" = '0' ]; then
+    echo "mulesQHDFoam compiled"
+else
+    echo "mulesQHDFoam compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd zQGDFoam; ./Allwmake; cd ../
+cd zQGDFoam; ./Allwmake
+if [ "$rc" = '0' ]; then
+    echo "zQGDFoam compiled"
+else
+    echo "zQGDFoam compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd interQHDFoam; ./Allwmake; cd ../
+cd interQHDFoam; ./Allwmake
+if [ "$rc" = '0' ]; then
+    echo "interQHDFoam compiled"
+else
+    echo "interQHDFoam compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd particlesQGDFoam; ./Allwmake; cd ../
+cd particlesQGDFoam; ./Allwmake
+if [ "$rc" = '0' ]; then
+    echo "particlesQGDFoam compiled"
+else
+    echo "particlesQGDFoam compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd particlesQHDFoam; ./Allwmake; cd ../
+cd particlesQHDFoam; ./Allwmake
+if [ "$rc" = '0' ]; then
+    echo "particlesQHDFoam compiled"
+else
+    echo "particlesQHDFoam compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd QHDDyMFoam; ./Allwmake; cd ../
+cd QHDDyMFoam; ./Allwmake
+if [ "$rc" = '0' ]; then
+    echo "QHDDyMFoam compiled"
+else
+    echo "QHDDyMFoam compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd SRFQHDFoam; ./Allwmake; cd ../
+cd SRFQHDFoam; ./Allwmake
+if [ "$rc" = '0' ]; then
+    echo "SRFQHDFoam compiled"
+else
+    echo "SRFQHDFoam compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd reactingLagrangianQGDFoam; ./Allwmake; cd ../
+cd reactingLagrangianQGDFoam; ./Allwmake
+if [ "$rc" = '0' ]; then
+    echo "reactingLagrangianQGDFoam compiled"
+else
+    echo "reactingLagrangianQGDFoam compiled with errors"
+    exit -1
+fi
+cd ../
 
-cd scalarTransportQHDFoam; ./Allwmake; cd ../
+cd scalarTransportQHDFoam; ./Allwmake
+if [ "$rc" = '0' ]; then
+    echo "scalarTransportQHDFoam compiled"
+else
+    echo "scalarTransportQHDFoam compiled with errors "
+    exit -1
+fi
+cd ../
 
-cd utils/selectBadCells; wmake; cd ../../
+cd utils/selectBadCells; wmake
+if [ "$rc" = '0' ]; then
+    echo "util selectBadCells compiled"
+else
+    echo "util selectBadCells compiled with errors"
+    exit -1
+fi
+cd ../../
 
 #
 #END-OF-FILE
 #
-
 
