add reactingQGDFoam solver

diff --git a/app/Allwmake b/app/Allwmake
--- a/app/Allwmake
+++ b/app/Allwmake
@@ -60,6 +60,16 @@ else
 fi
 cd ../
 
+cd reactingQGDFoam; ./Allwmake
+rc=$?
+if [ "$rc" = '0' ]; then
+    echo "reactingQGDFoam compiled"
+else
+    echo "reactingQGDFoam compiled with errors"
+    exit -1
+fi
+cd ../
+
 cd particlesQHDFoam; ./Allwmake
 rc=$?
 if [ "$rc" = '0' ]; then
